version: '3'

services:
  master:
    build: .
    command: go run main.go master
    ports:
      - "8080:8080"
    depends_on:
      - node1
      - node2

  node1:
    build: .
    command: go run main.go node1
    hostname: node1
    ports:
      - "9001:9001"

  node2:
    build: .
    command: go run main.go node2
    hostname: node2
    ports:
      - "9002:9002"
